apiVersion: v1
kind: LimitRange
metadata:
  name: my-limit-range
  namespace: my-namespace
spec:
  limits:
    - type: Container
      default:
        memory: 512Mi
        cpu: 500m
      max:
        memory: 1Gi
        cpu: 1
      min:
        memory: 100Mi
        cpu: 100m
