apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
  - name: my-container
    image: nginx
    env:
      - name: APP_NAME
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: APP_NAME
      - name: LOG_LEVEL
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: LOG_LEVEL
